name: Build and deploy Aseprite   # 左侧显示的名字

on:
  workflow_dispatch:              # 允许手动
  schedule:
    - cron: '0 2 * * *'           # 每天 02:00 UTC

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Aseprite source
        uses: actions/checkout@v4
        with:
          repository: aseprite/aseprite
          ref: main
          submodules: recursive

      - name: Install build tools
        run: |
          choco install cmake ninja

      - name: Download Skia
        run: |
          Invoke-WebRequest -Uri https://github.com/aseprite/skia/releases/download/m102/Skia-m102-Win-Release-x64.zip -OutFile Skia-m102-Win-Release-x64.zip
          if (!(Test-Path Skia-m102-Win-Release-x64.zip)) { exit 1 }
          7z x Skia-m102-Win-Release-x64.zip -oskia

      - name: Configure & Compile
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo ^
                -DLAF_BACKEND=skia ^
                -DSKIA_DIR=%CD%\skia ^
                -DSKIA_LIBRARY_DIR=%CD%\skia\out\Release-x64
          ninja -C build aseprite

      - name: Pack artifact
        run: |
          7z a Aseprite-win64.zip .\build\bin\aseprite.exe .\build\bin\data

      - name: Upload to release
        uses: ncipollo/release-action@v1
        with:
          tag: nightly-${{ github.run_number }}
          name: Nightly build ${{ github.run_number }}
          artifacts: Aseprite-win64.zip
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
